---
- name: Pull docker image of speminiproject
  hosts: all
  tasks:
    - name: Pull image
      docker_image:
        name: jaswanth6008/devops
        tag: latest
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
          name: calculator-using-devops
          image: jaswanth6008/devops
          state: started
          tty: yes
          interactive: yes