---
- hosts: localhost
  tasks:
  - name: Pull docker image of speminiproject
    hosts: all
    tasks:
      - name: Pull image
        docker_image:
          name: jaswanth6008/devops
          source: pull